config/routes.rb
Rails.application.routes.draw do
 match 'base_articles/new'=>'base_articles#new', via: [:get, :post]
 match 'base_articles/edit/:id'=>'base_articles#edit', via: [:get, :post]
 match 'base_articles/:id'=>'base_articles#update', via: [:get, :post]
 resources :authors
 resources :base_articles
 resources :authors


end

app/models/author.rb
class Author < ActiveRecord::Base
	has_many :base_article_authors
has_many :articles , :through=>:base_article_authors
end

app/models/base_article.rb
class BaseArticle < ActiveRecord::Base
has_many :base_article_authors
has_many :authors , :through=>:base_article_authors
has_many :image_properties, :as => :entity


# searchable do
#   integer :id
#   text :title, :stored => true
#   text :content, :stored => true
#   text :description
#   integer :author_ids, :multiple => true
# end


def article_id
  BaseArticle.all.collect(&:id) if !BaseArticle.all.blank?
end

def article_authors
 Author.all.collect(&:id)  if !BaseArticle.all.blank?
end


 def self.article_search(query,page=1,per_page=10)
 @results= results = BaseArticle.search do
    fulltext query do
      boost_fields :title => 3.0
      highlight :content
    end
    facet(:author_ids)
    paginate :page => page, :per_page => per_page
  end 
  return @results
 end

 def base_article_image=(profle_image)
  self.image_properties.delete_all if !self.image_properties.blank?
  if !profle_image.blank?
  image=BaseImage.find(profle_image)
  image_path = image.resize_image(100,100)
  image_property = self.image_properties.new(:image_id=>profle_image,:entity_type=>"BaseArticle",:image_path=>image_path)
  end
 end 
# after_create do |article|
#   article.index!
# end

# after_update do |article|
#   article.index!
# end
end

app/models/base_article_author.rb
class BaseArticleAuthor < ActiveRecord::Base
 belongs_to :base_article
 belongs_to :author
end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController
  before_action :set_author, only: [:show, :edit, :update, :destroy]

  # GET /authors
  def index
    @authors = Author.all
  end

  # GET /authors/1
  def show
  end

  # GET /authors/new
  def new
    @author = Author.new
  end

  # GET /authors/1/edit
  def edit
  end

  # POST /authors
  def create
    @author = Author.new(author_params)

    if @author.save
      redirect_to @author, notice: 'Author was successfully created.'
    else
      render action: 'new'
    end
  end

  # PATCH/PUT /authors/1
  def update
    if @author.update(author_params)
      redirect_to @author, notice: 'Author was successfully updated.'
    else
      render action: 'edit'
    end
  end

  # DELETE /authors/1
  def destroy
    @author.destroy
    redirect_to authors_url, notice: 'Author was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_author
      @author = Author.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def author_params
      params.require(:author).permit(:name, :address, :description)
    end
end

app/controllers/base_articles_controller.rb
class BaseArticlesController < ApplicationController
  before_action :set_base_article, only: [:show, :edit, :update, :destroy]
  layout "article_application"
  # GET /base_articles
  def index
    @base_articles = BaseArticle.paginate(:page => params[:page], :per_page => 2,:order=>"id DESC")
    if !params[:page].blank?
     render :template=>"/base_articles/index",:layout =>false
    else
     render :template=>"/base_articles/index"
    end 
  end

  # GET /base_articles/1
  def show
  end

  # GET /base_articles/new
  def new
    @base_article = BaseArticle.new
  end

  # GET /base_articles/1/edit
  def edit
  end

  # POST /base_articles
  def create
    @base_article = BaseArticle.new(base_article_params)

    if @base_article.save
      redirect_to action:"index", notice: 'Base article was successfully created.'
    else
      render action: 'new'
    end
  end

  # PATCH/PUT /base_articles/1
  def update
    if @base_article.update(base_article_params)
      redirect_to action:"index",notice: 'Base article was successfully updated.'
    else
      render action: 'edit'
    end
  end

  # DELETE /base_articles/1
  def destroy
    @base_article.destroy
    redirect_to base_articles_url, notice: 'Base article was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_base_article
      debugger
      @base_article = BaseArticle.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def base_article_params
      params.require(:base_article).permit(:title, :content,:medium,:description,:base_article_image)
    end
end

app/helpers/authors_helper.rb
module AuthorsHelper
end

app/helpers/base_article_helper.rb
module BaseArticleHelper
end

app/helpers/base_articles_helper.rb
module BaseArticlesHelper
end

app/views/authors/_form.html.erb
<%= form_for(@author) do |f| %>
  <% if @author.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@author.errors.count, "error") %> prohibited this author from being saved:</h2>

      <ul>
      <% @author.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :address %><br>
    <%= f.text_area :address %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/authors/_index.html.erb
<% object.each do |obj|%>
 <tr>
   <% header_include.each do |a|%>
    <td><%=obj.send(a)%></td>
   <% end %>
 </tr>
<% end%>

app/views/authors/edit.html.erb
<h1>Editing author</h1>

<%= render 'form' %>

<%= link_to 'Show', @author %> |
<%= link_to 'Back', authors_path %>

app/views/authors/index.html.erb
<h1>Listing authors</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Address</th>
      <th>Description</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @authors.each do |author| %>
      <tr>
        <td><%= author.name %></td>
        <td><%= author.address %></td>
        <td><%= author.description %></td>
        <td><%= link_to 'Show', author %></td>
        <td><%= link_to 'Edit', edit_author_path(author) %></td>
        <td><%= link_to 'Destroy', author, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Author', new_author_path %>

app/views/authors/new.html.erb
<h1>New author</h1>

<%= render 'form' %>

<%= link_to 'Back', authors_path %>

app/views/authors/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @author.name %>
</p>

<p>
  <strong>Address:</strong>
  <%= @author.address %>
</p>

<p>
  <strong>Description:</strong>
  <%= @author.description %>
</p>

<%= link_to 'Edit', edit_author_path(@author) %> |
<%= link_to 'Back', authors_path %>

app/views/base_articles/_form.html.erb
<%if @base_article.new_record?%>
<%=form_tag(:controller=>'base_articles',:action=>'create') %>
<%else%>
<%=form_tag(:controller=>'base_articles',:action=>'update',:id=>@base_article.id)%>
<%end%>
  <% if @base_article.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@article.errors.count, "error") %> prohibited this article from being saved:</h2>

      <ul>
      <% @base_article.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <label for="name">Title:</label><%=text_field("base_article","title")%>
  </div>  
  <%=hidden_field_tag("id",@base_article.id) if !@base_article.blank?%>
  <div class="field">
   <label for="name">Author:</label>
    <%= select_tag "base_article[author_ids][]", options_for_select(Author.all.collect{|x| [x.name,x.id]},@base_article.author_ids), {:multiple => :multiple, :size => 10} %>
  </div>
  <div class="field">
        <label for="name">Description:</label><%=text_field("base_article","description")%></p>
  </div>
    <div class="field">
    <label for="name">Content:</label>
    <script type="text/javascript" src="/tinymce/jscripts/tiny_mce/tiny_mce.js"></script>
<script type="text/javascript">
  tinyMCE.init({
    // General options
    mode : "textareas",
    theme : "advanced",
    plugins : "autolink,lists,pagebreak,style,layer,table,save,advhr,advimage,advlink,emotions,iespell,inlinepopups,insertdatetime,preview,media,searchreplace,print,contextmenu,paste,directionality,fullscreen,noneditable,visualchars,nonbreaking,xhtmlxtras,template,wordcount,advlist,autosave,visualblocks",

    // Theme options
    theme_advanced_buttons1 : "save,newdocument,|,bold,italic,underline,strikethrough,|,justifyleft,justifycenter,justifyright,justifyfull,styleselect,formatselect,fontselect,fontsizeselect",
    theme_advanced_buttons2 : "cut,copy,paste,pastetext,pasteword,|,search,replace,|,bullist,numlist,|,outdent,indent,blockquote,|,undo,redo,|,link,unlink,anchor,image,cleanup,help,code,|,insertdate,inserttime,preview,|,forecolor,backcolor",
    theme_advanced_buttons3 : "tablecontrols,|,hr,removeformat,visualaid,|,sub,sup,|,charmap,emotions,iespell,media,advhr,|,print,|,ltr,rtl,|,fullscreen",
    theme_advanced_buttons4 : "insertlayer,moveforward,movebackward,absolute,|,styleprops,|,cite,abbr,acronym,del,ins,attribs,|,visualchars,nonbreaking,template,pagebreak,restoredraft,visualblocks",
    theme_advanced_toolbar_location : "top",
    theme_advanced_toolbar_align : "left",
    theme_advanced_statusbar_location : "bottom",
    theme_advanced_resizing : true,

    // Example content CSS (should be your site CSS)
    content_css : "css/content.css",

    // Drop lists for link/image/media/template dialogs
    template_external_list_url : "lists/template_list.js",
    external_link_list_url : "lists/link_list.js",
    external_image_list_url : "lists/image_list.js",
    media_external_list_url : "lists/media_list.js",
                extended_valid_elements: "iframe[src|width|height|name|align], embed[width|height|name|flashvars|src|bgcolor|align|play|loop|quality| allowscriptaccess|type|pluginspage]",
    // Style formats
    style_formats : [
      {title : 'Bold text', inline : 'b'},
      {title : 'Red text', inline : 'span', styles : {color : '#ff0000'}},
      {title : 'Red header', block : 'h1', styles : {color : '#ff0000'}},
      {title : 'Example 1', inline : 'span', classes : 'example1'},
      {title : 'Example 2', inline : 'span', classes : 'example2'},
      {title : 'Table styles'},
      {title : 'Table row 1', selector : 'tr', classes : 'tablerow1'}
    ],

    // Replace values for the template plugin
    template_replace_values : {
      username : "Some User",
      staffid : "991234"
    }
  });
</script>
<!-- /TinyMCE -->.
<textarea id="elm1" name="base_article[content]" rows="15" cols="30" style="width: 50%"><%=@base_article.content%></textarea>
     <%#=text_field("articel","content")%></p>
  </div>
  <div class="field">
  <p id="after_upload"><label for="name">Profile Image:</label><a href="/image?popup=true" title="profile image" class="windowpopup">Insert Image</a></p>
 <p id="before_upload" style="display:none">
 <%=hidden_field_tag("base_article[base_article_image]","",:id=>"profile_image_id")%>
 <%=image_tag("",:alt=>"profile_image",:id=>"profile_image")%>
</p>
</div>
  <div class="field">
    <label for="name">Text Medium:<%=radio_button_tag 'base_article[medium]', 'text'%>
    Video Medium:<%=radio_button_tag 'base_article[medium]', 'video'%></label>
  </div>
  </div>
  <div class="actions">
    <%= submit_tag("submit") %>
  </div>
<style>
form{margin-left: 27px;}
#scroll-container h1 {margin-left: 27px;}
label {float: left;}
</style>

app/views/base_articles/_index.html.erb
<% object.each do |obj|%>
  <!--div class="img"-->
    <%if obj.medium =='text'%>  
    <div class="span4">
      <div class="caption">
     <div class="item">         
      <% header_include.each do |a|%>
       <%=raw obj.send(a)%>
      <% end %>
      <%=image_tag(obj.image_properties.first.image_path) if !obj.image_properties.blank?%>
      </div>
     </div> 
    </div>
   <%else%>
    <div class="span4">
     <div class="item">
       <%=raw obj.content%>
    </div>
   </div> 
   <%end%>
  <!--/div-->
<% end%>

app/views/base_articles/edit.html.erb
<h1>Editing article</h1>

<%= render 'form' %>

<%= link_to 'Show', @base_article %> |
<%= link_to 'Back', base_articles_path %>

app/views/base_articles/index.html.erb
<div class="content">
	 <%cache("component2") do%>
      <%=raw render_template_in_format({:object=>@base_articles,:header_include=>[],:main_header=>{'id'=>'Id',"title"=>"Title","content"=>"Content"},:decoration=>"/decoration/decoration_empty",:partial=>"/base_articles/index"})%>
       <%end%>	
</div>

app/views/base_articles/new.html.erb
<h1>New article</h1>

<%= render 'form' %>

<%= link_to 'Back', base_articles_path %>

app/views/base_articles/search.html.erb
<h1>Listing articles</h1>
<%= link_to 'New Article', new_article_path %>
<div id="facets">
  <h3>Authors</h3>
  <ul>
    <% for row in @results.facet(:author_ids).rows %>  
      <li>
          <strong><%= Author.find(row.value).name if row%> (<%= row.count %>)</strong>
      </li>
    <% end %>
  </ul>
</div>
<table width="100%"  border="0">
  <tr class="decoration_tr" valign="top">
    <td class='main_td'>
       <%cache("component2") do%>
      <%=raw render_template_in_format({:object=>@base_articles,:header_include=>[],:main_header=>{'id'=>'Id',"title"=>"Title","content"=>"Content"},:decoration=>"/decoration/decoration",:partial=>"/pagenates/index"})%>
       <%end%>
      <%#=raw render_template_in_format({:object=>Person.all,:header_include=>['id'],:main_header=>{'id'=>'You Tube Video'},:decoration=>"/decoration/decoration_empty",:partial=>"/pagenates/you_tube_video"})%>
    </td>
</table>

app/views/base_articles/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Title:</b>
  <%= @base_article.title %>
</p>

<p>
  <b>Description:</b>
  <%= @base_article.description %>
</p>

<p>
  <b>Content:</b>
  <%= @base_article.content %>
</p>


<%= link_to 'Edit', edit_article_path(@base_article) %> |
<%= link_to 'Back', base_articles_path %>

app/views/decoration/_decoration.html.erb
<table class="table_structure">
 <thead>
  <tr>
   <%header_include.each do |a|%>
     <th> <%=(!main_header.blank? and main_header.keys.include?a) ? main_header[a] : a %></th>
   <%end%>
  </tr>
 </thead>
 <tbody>
   <%=yield%>
 </tbody>
</table>
<style type="text/css">
  .table_border{border-top-width: 1px;border-right-width: 1px;border-bottom-width: 1px;border-left-width: 1px; }
</style>

app/views/decoration/_decoration_empty.html.erb
<%=yield%>

app/views/decoration/_index.html.erb
<% object.each do |obj|%>
 <tr>
   <% header_include.each do |a|%>
    <td><%=obj.send(a)%></td>
   <% end %>
 </tr>
<% end%>

app/views/layouts/article_application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />	
	<title>Responsive Web Mobile</title>

	<!-- Set the viewport width to device width for mobile -->
  	<meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- Included Bootstrap CSS Files -->
	<link rel="stylesheet" href="/stylesheets/bootstrap/css/bootstrap.min.css" />
	<link rel="stylesheet" href="/stylesheets/bootstrap/css/bootstrap-responsive.min.css" />
	
	<script src="/javascripts/jquery-1.10.0.min.js"></script>
	<script src="/javascripts/bootstrap/js/bootstrap.min.js"></script>
	<script src="/javascripts/script.js"></script>
	<script  type="text/javascript" src="/javascripts/jquery.popupWindow.js"></script>

	<!-- Css -->	
	<link rel="stylesheet" href="/stylesheets/article_style.css" />
    <%= csrf_meta_tags %>
</head>
<body id="start">
      <%=render :partial=>"/layouts/menu"%>

	<!-- This is the overlay DIV that is displayed while loading a new page -->
	<div id="loader"></div>

	<div class="container">
		<div class="row">
			<div class="span12">
				<div class="hero-unit">
					<h1>Infinite Scroll</h1>
					<p class="">here is a simple example of a infinite scroll!</p>
				</div>
			</div>
			<% if @current_user %>
             Logged in as <%= @current_user.email %>
             <%= link_to "Log out", :controller=>"login",:action=>"logout"  %>
            <% else %>
            <% end %>
		</div>
		<!-- This is the main container (#scroll-container) -->
		<div id="scroll-container" class="row">
			<%= yield %>
		</div>
	</div>
   
	<!-- These are all the links that can be loaded. -->
	<%if !@base_articles.blank?%>
	<div id="pages">
		<%=will_paginate(@base_articles)%>
	</div>
	<%end%>
	</body>
<script type="text/javascript">
jQuery('.windowpopup').popupWindow({ 
height:500, 
width:800, 
top:50, 
scrollbars:true,
left:50 
});
</script>
<style type="text/css">
 .span4 {
 	height:"200";
    background-color: #DCDCDC;
    margin-top: 10px;
 }
 body{
 	margin: 0;
font-family: "Helvetica Neue",Helvetica,Arial,sans-serif;
font-size: 14px;
line-height: 20px;
color: #333;
height:750px;
background: -webkit-linear-gradient(left top, red , yellow); /* For Safari 5.1 to 6.0 */
background: -o-linear-gradient(bottom right, red, yellow); /* For Opera 11.1 to 12.0 */
background: -moz-linear-gradient(bottom right, red, yellow); /* For Firefox 3.6 to 15 */
background: linear-gradient(to bottom right, red , yellow); /* Standard syntax (must be last) */
padding-bottom: 40px;
padding-top: 60px;
 }
</style>
</html>